[tools]
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "1.2.4"
"vfox-pulumi:pulumi/pulumi-random" = "4.18.5"
"vfox-pulumi:pulumiverse/pulumi-time" = "latest"
"vfox-pulumi:pulumi/pulumi-std" = "2.2.0"
