[tools]
golangci-lint = "2.7.0"
"go:gotest.tools/gotestsum" = "1.12.0"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "1.2.4"
"vfox-pulumi:pulumi/pulumi-random" = "4.18.5"
"vfox-pulumi:pulumiverse/pulumi-time" = "0.1.1"
"vfox-pulumi:pulumi/pulumi-std" = "2.2.0"
